const nlp = require('compromise');
const Fuse = require('fuse.js');

// Function to analyze task priority based on title and description
function analyzeTaskPriority(title, description) {
  const doc = nlp(title + ' ' + description);

  // Check for urgency keywords
  const urgentWords = doc.match('urgent|asap|immediately|important|priority');
  const deadlineWords = doc.match('deadline|due|by tomorrow|soon');

  if (urgentWords.found || deadlineWords.found) {
    return 'High';
  }

  // Check for low priority indicators
  const lowPriorityWords = doc.match('someday|eventually|whenever|later');
  if (lowPriorityWords.found) {
    return 'Low';
  }

  return 'Medium'; // Default priority
}

// Function to extract keywords from task description for tagging
function extractKeywords(text) {
  const doc = nlp(text);
  const nouns = doc.nouns().out('frequency');
  // Return top 5 nouns as keywords
  return nouns.slice(0, 5).map(item => item.normal);
}

// Fuse.js options for fuzzy search on tasks
const fuseOptions = {
  keys: ['title', 'description', 'tags'],
  threshold: 0.3,
  includeScore: true,
};

// Function to perform fuzzy search on tasks array
function searchTasks(tasks, pattern) {
  const fuse = new Fuse(tasks, fuseOptions);
  return fuse.search(pattern).map(result => result.item);
}

// Function to generate AI suggestions based on user input
function generateAISuggestions(input, existingTasks = []) {
  const suggestions = [];
  const doc = nlp(input.toLowerCase());

  // Common task patterns and their suggestions
  const taskPatterns = {
    'meeting': [
      { title: 'Schedule team meeting', description: 'Organize and schedule a team meeting to discuss project updates', tags: ['meeting', 'team', 'planning'], priority: 'Medium' },
      { title: 'Prepare meeting agenda', description: 'Create agenda and talking points for upcoming meeting', tags: ['meeting', 'preparation', 'agenda'], priority: 'High' }
    ],
    'email': [
      { title: 'Send follow-up email', description: 'Send follow-up email to client or team member', tags: ['email', 'communication', 'follow-up'], priority: 'Medium' },
      { title: 'Check inbox', description: 'Review and respond to important emails', tags: ['email', 'communication', 'inbox'], priority: 'High' }
    ],
    'project': [
      { title: 'Update project status', description: 'Update project progress and share with stakeholders', tags: ['project', 'status', 'update'], priority: 'High' },
      { title: 'Review project timeline', description: 'Review project milestones and deadlines', tags: ['project', 'timeline', 'review'], priority: 'Medium' }
    ],
    'code': [
      { title: 'Code review', description: 'Review code changes and provide feedback', tags: ['code', 'review', 'development'], priority: 'High' },
      { title: 'Fix bug', description: 'Identify and fix software bug', tags: ['code', 'bug', 'fix'], priority: 'High' }
    ],
    'report': [
      { title: 'Generate weekly report', description: 'Create and send weekly progress report', tags: ['report', 'weekly', 'progress'], priority: 'Medium' },
      { title: 'Update documentation', description: 'Update project documentation and guides', tags: ['documentation', 'update', 'guide'], priority: 'Low' }
    ],
    'call': [
      { title: 'Schedule phone call', description: 'Schedule important phone call or video conference', tags: ['call', 'phone', 'schedule'], priority: 'Medium' },
      { title: 'Return missed calls', description: 'Return missed calls and follow up on messages', tags: ['call', 'follow-up', 'communication'], priority: 'High' }
    ]
  };

  // Check for keywords in user input
  for (const [keyword, tasks] of Object.entries(taskPatterns)) {
    if (doc.has(keyword) || input.toLowerCase().includes(keyword)) {
      suggestions.push(...tasks);
    }
  }

  // If no specific patterns match, generate generic suggestions based on input
  if (suggestions.length === 0) {
    const priority = analyzeTaskPriority(input, '');
    const tags = extractKeywords(input);
    suggestions.push({
      title: input.charAt(0).toUpperCase() + input.slice(1),
      description: `Complete task: ${input}`,
      tags: tags.length > 0 ? tags : ['task'],
      priority: priority
    });
  }

  // Limit to 5 suggestions and ensure variety
  return suggestions.slice(0, 5);
}

// Function to generate AI description suggestions based on task title
function generateAIDescription(title) {
  const doc = nlp(title.toLowerCase());
  let description = '';

  // Common task types and their descriptions
  const taskDescriptions = {
    'meeting': 'Schedule and conduct a meeting to discuss important topics, share updates, and collaborate with team members.',
    'email': 'Send an email to communicate important information, follow up on previous conversations, or coordinate with others.',
    'call': 'Make a phone call or video conference to discuss matters, provide updates, or resolve issues in real-time.',
    'report': 'Create and prepare a report documenting progress, findings, or analysis for stakeholders or management.',
    'review': 'Conduct a thorough review of work, documents, or processes to ensure quality and identify improvements.',
    'plan': 'Develop a plan or strategy for upcoming tasks, projects, or activities to ensure successful execution.',
    'update': 'Provide an update on current status, progress, or changes to keep everyone informed and aligned.',
    'research': 'Conduct research to gather information, analyze data, and provide insights for decision-making.',
    'test': 'Perform testing to verify functionality, identify issues, and ensure quality before deployment.',
    'fix': 'Identify and resolve issues, bugs, or problems to restore proper functionality.',
    'design': 'Create or improve design elements, user interfaces, or visual components for better user experience.',
    'document': 'Create or update documentation to record processes, procedures, or important information.',
    'organize': 'Organize files, data, or resources to improve efficiency and accessibility.',
    'schedule': 'Plan and arrange appointments, events, or activities for optimal timing and coordination.',
    'budget': 'Manage financial planning, cost analysis, or budget-related activities.',
    'training': 'Provide or receive training to develop skills, knowledge, or competencies.',
    'presentation': 'Prepare and deliver a presentation to communicate ideas, results, or information effectively.',
    'analysis': 'Perform detailed analysis of data, trends, or situations to gain insights and make informed decisions.',
    'backup': 'Create backups of important data, files, or systems to prevent data loss.',
    'security': 'Implement or review security measures to protect systems, data, and information.',
    'maintenance': 'Perform routine maintenance tasks to ensure systems and equipment function properly.',
    'purchase': 'Handle procurement, purchasing, or acquisition of goods, services, or resources.',
    'interview': 'Conduct interviews for hiring, research, or information gathering purposes.',
    'survey': 'Create and distribute surveys to collect feedback, opinions, or data from respondents.',
    'audit': 'Conduct an audit to review processes, compliance, or performance against standards.',
    'clean': 'Clean, organize, or maintain physical or digital spaces and resources.',
    'setup': 'Configure, install, or set up systems, equipment, or environments for use.',
    'monitor': 'Monitor systems, processes, or activities to track performance and identify issues.',
    'optimize': 'Improve efficiency, performance, or processes through analysis and implementation of changes.',
    'deploy': 'Deploy software, systems, or updates to production environments.',
    'migrate': 'Move data, systems, or applications from one environment to another.',
    'integrate': 'Connect different systems, applications, or processes to work together seamlessly.',
    'validate': 'Verify accuracy, completeness, or compliance of data, processes, or results.',
    'archive': 'Store and organize historical data, documents, or records for future reference.',
    'coordinate': 'Organize and manage activities, resources, or people to achieve common goals.',
    'negotiate': 'Discuss terms, conditions, or agreements to reach mutually beneficial outcomes.',
    'evaluate': 'Assess performance, quality, or effectiveness of processes, products, or services.',
    'implement': 'Put plans, strategies, or solutions into action and ensure successful execution.',
    'collaborate': 'Work together with others to achieve shared objectives and goals.',
    'communicate': 'Exchange information, ideas, or updates with relevant stakeholders.',
    'prioritize': 'Identify and rank tasks or activities based on importance and urgency.',
    'delegate': 'Assign tasks or responsibilities to appropriate team members.',
    'follow-up': 'Check on progress, provide feedback, or ensure completion of previous actions.',
    'brainstorm': 'Generate creative ideas and solutions through group discussion and thinking.',
    'prototype': 'Create initial versions or models to test concepts and gather feedback.',
    'benchmark': 'Compare performance against standards or competitors to identify areas for improvement.',
    'troubleshoot': 'Identify and resolve technical or operational problems and issues.',
    'standardize': 'Establish consistent processes, procedures, or formats across systems or teams.',
    'streamline': 'Simplify and improve processes to increase efficiency and reduce complexity.',
    'automate': 'Implement automated solutions to reduce manual effort and improve consistency.',
    'customize': 'Adapt systems, processes, or products to meet specific requirements or preferences.',
    'calibrate': 'Adjust and fine-tune systems, equipment, or processes for optimal performance.',
    'simulate': 'Create models or scenarios to test outcomes and predict results.',
    'forecast': 'Predict future trends, demands, or outcomes based on data and analysis.',
    'profile': 'Analyze user behavior, preferences, or characteristics to improve services.',
    'segment': 'Divide data, users, or markets into distinct groups for targeted approaches.',
    'personalize': 'Customize experiences or content based on individual preferences or behavior.',
    'authenticate': 'Verify identity or access rights to ensure security and proper authorization.',
    'encrypt': 'Protect data and communications using encryption methods and technologies.',
    'compress': 'Reduce file sizes or data volumes to optimize storage and transmission.',
    'synchronize': 'Ensure consistency and alignment between different systems or data sources.',
    'virtualize': 'Create virtual environments or resources to improve flexibility and efficiency.',
    'containerize': 'Package applications and dependencies for consistent deployment across environments.',
    'orchestrate': 'Coordinate and manage complex workflows or processes across multiple systems.',
    'instrument': 'Add monitoring and logging capabilities to track system behavior and performance.',
    'profile-performance': 'Analyze performance characteristics to identify bottlenecks and optimization opportunities.',
    'refactor': 'Restructure code or systems to improve maintainability and performance.',
    'modularize': 'Break down complex systems into smaller, manageable components.',
    'abstract': 'Create simplified interfaces or representations to hide complexity.',
    'normalize': 'Standardize data structures and relationships for consistency and efficiency.',
    'denormalize': 'Optimize data structures for specific query patterns and performance needs.',
    'shard': 'Distribute data across multiple databases or servers for scalability.',
    'replicate': 'Create copies of data or systems for redundancy and availability.',
    'cluster': 'Group servers or resources together for high availability and load balancing.',
    'load-balance': 'Distribute workload across multiple resources to optimize performance.',
    'cache': 'Store frequently accessed data in memory for faster retrieval.',
    'index': 'Create data structures to enable fast searching and retrieval.',
    'partition': 'Divide data or systems into smaller, more manageable segments.',
    'aggregate': 'Combine and summarize data from multiple sources for analysis.',
    'transform': 'Convert data from one format or structure to another.',
    'extract': 'Pull data from various sources for processing and analysis.',
    'load': 'Import processed data into target systems or databases.',
    'ingest': 'Collect and import large volumes of data from multiple sources.',
    'stream': 'Process continuous flows of data in real-time.',
    'batch': 'Process data in groups or batches at scheduled intervals.',
    'real-time': 'Process and analyze data as it becomes available.',
    'historical': 'Analyze past data to identify trends and patterns.',
    'predictive': 'Use data and algorithms to forecast future outcomes.',
    'prescriptive': 'Provide recommendations for optimal actions based on data analysis.',
    'diagnostic': 'Identify root causes of problems or issues through data analysis.',
    'exploratory': 'Investigate data to discover patterns, relationships, and insights.',
    'confirmatory': 'Test hypotheses and validate assumptions using statistical methods.',
    'descriptive': 'Summarize and describe data characteristics and distributions.',
    'inferential': 'Draw conclusions about populations based on sample data.',
    'causal': 'Determine cause-and-effect relationships between variables.',
    'correlational': 'Identify relationships and associations between variables.',
    'regression': 'Model relationships between dependent and independent variables.',
    'classification': 'Categorize data into predefined classes or groups.',
    'clustering': 'Group similar data points together based on characteristics.',
    'anomaly': 'Detect unusual patterns or outliers in data.',
    'recommendation': 'Suggest items, actions, or content based on user preferences.',
    'sentiment': 'Analyze text to determine emotional tone and opinions.',
    'topic': 'Identify main themes and subjects in text or documents.',
    'summarization': 'Create concise summaries of longer texts or documents.',
    'translation': 'Convert text from one language to another.',
    'extraction': 'Pull specific information or entities from unstructured text.',
    'generation': 'Create new content or text based on patterns and examples.',
    'completion': 'Fill in missing parts of text or predict next elements.',
    'correction': 'Identify and fix errors in text or data.',
    'parsing': 'Analyze text structure and extract grammatical components.',
    'tokenization': 'Break text into smaller units like words or sentences.',
    'stemming': 'Reduce words to their root or base forms.',
    'lemmatization': 'Convert words to their canonical dictionary forms.',
    'pos-tagging': 'Assign grammatical categories to words in text.',
    'ner': 'Identify and classify named entities in text.',
    'coreference': 'Resolve references between pronouns and their antecedents.',
    'similarity': 'Measure how similar two pieces of text or data are.',
    'embedding': 'Convert text or data into numerical vector representations.',
    'attention': 'Focus on relevant parts of input data for processing.',
    'transformer': 'Use self-attention mechanisms for sequence processing.',
    'recurrent': 'Process sequential data using recurrent neural networks.',
    'convolutional': 'Apply convolutional operations for pattern recognition.',
    'autoencoder': 'Learn efficient data representations through encoding/decoding.',
    'gan': 'Generate new data using generative adversarial networks.',
    'reinforcement': 'Learn optimal actions through trial and error.',
    'supervised': 'Learn from labeled training data.',
    'unsupervised': 'Discover patterns in unlabeled data.',
    'semi-supervised': 'Learn from partially labeled data.',
    'transfer': 'Apply knowledge from one task to another.',
    'few-shot': 'Learn from very few examples.',
    'zero-shot': 'Perform tasks without specific training examples.',
    'meta-learning': 'Learn how to learn new tasks quickly.',
    'federated': 'Train models across decentralized devices or servers.',
    'distributed': 'Train models across multiple computing resources.',
    'parallel': 'Process data simultaneously across multiple processors.',
    'asynchronous': 'Perform operations without waiting for completion.',
    'synchronous': 'Coordinate operations to happen at the same time.',
    'batch-processing': 'Process multiple items together efficiently.',
    'streaming': 'Process data continuously as it arrives.',
    'micro-batch': 'Process small batches of streaming data.',
    'lambda': 'Handle both batch and streaming data processing.',
    'kappa': 'Simplify architecture by focusing on streaming processing.',
    'event-driven': 'Respond to events and changes in real-time.',
    'reactive': 'Build systems that respond to changes automatically.',
    'serverless': 'Run code without managing servers or infrastructure.',
    'container': 'Package applications with their dependencies.',
    'orchestration': 'Manage and coordinate containerized applications.',
    'service-mesh': 'Manage service-to-service communication in microservices.',
    'api-gateway': 'Manage and route API requests in microservices.',
    'circuit-breaker': 'Prevent cascading failures in distributed systems.',
    'bulkhead': 'Isolate failures to prevent system-wide impact.',
    'retry': 'Automatically retry failed operations.',
    'timeout': 'Set time limits for operations to prevent hanging.',
    'fallback': 'Provide alternative responses when primary operations fail.',
    'rate-limiting': 'Control the rate of requests to prevent overload.',
    'throttling': 'Slow down request processing to manage load.',
    'caching': 'Store frequently accessed data for faster retrieval.',
    'memoization': 'Cache results of expensive function calls.',
    'lazy-loading': 'Load data only when needed.',
    'eager-loading': 'Load all required data upfront.',
    'pagination': 'Divide large datasets into smaller, manageable pages.',
    'virtualization': 'Create virtual versions of physical resources.',
    'emulation': 'Mimic the behavior of one system on another.',
    'simulation': 'Model real-world processes for testing and analysis.',
    'prototyping': 'Create early versions of products for testing.',
    'mocking': 'Create fake versions of components for testing.',
    'stubbing': 'Replace complex components with simple implementations.',
    'spying': 'Monitor method calls and interactions during testing.',
    'assertion': 'Verify that code behaves as expected.',
    'fixture': 'Set up test data and environment.',
    'harness': 'Framework for running and managing tests.',
    'coverage': 'Measure how much code is exercised by tests.',
    'mutation': 'Test test suites by introducing code changes.',
    'property-based': 'Test based on general properties rather than specific examples.',
    'integration': 'Test how different components work together.',
    'unit': 'Test individual units or components in isolation.',
    'system': 'Test the entire system as a whole.',
    'acceptance': 'Test that meets business requirements.',
    'performance': 'Test system performance under load.',
    'load': 'Test system behavior under heavy load.',
    'stress': 'Test system limits and failure points.',
    'volume': 'Test with large amounts of data.',
    'scalability': 'Test ability to handle growth.',
    'compatibility': 'Test across different environments and configurations.',
    'usability': 'Test user experience and interface design.',
    'accessibility': 'Test for users with disabilities.',
    'security': 'Test for vulnerabilities and threats.',
    'penetration': 'Simulate attacks to find security weaknesses.',
    'vulnerability': 'Identify and assess security risks.',
    'compliance': 'Test adherence to regulations and standards.',
    'audit': 'Review and verify system security and compliance.',
    'encryption': 'Test data protection and secure communication.',
    'authentication': 'Test user identity verification.',
    'authorization': 'Test access control and permissions.',
    'session': 'Test user session management.',
    'input-validation': 'Test handling of user input and data.',
    'output-encoding': 'Test proper encoding of output data.',
    'error-handling': 'Test system response to errors and exceptions.',
    'logging': 'Test logging of events and activities.',
    'monitoring': 'Test system monitoring and alerting.',
    'alerting': 'Test notification systems for issues.',
    'dashboard': 'Test monitoring dashboards and visualizations.',
    'metrics': 'Test collection and analysis of system metrics.',
    'tracing': 'Test request tracing through distributed systems.',
    'profiling': 'Test performance profiling and optimization.',
    'benchmarking': 'Test against performance standards.',
    'optimization': 'Test performance improvement techniques.',
    'tuning': 'Test system configuration optimization.',
    'scaling': 'Test system growth and resource management.',
    'balancing': 'Test load distribution across resources.',
    'failover': 'Test automatic switching to backup systems.',
    'recovery': 'Test system recovery from failures.',
    'backup': 'Test data backup and restoration.',
    'disaster': 'Test response to major system failures.',
    'continuity': 'Test business continuity planning.',
    'redundancy': 'Test backup systems and components.',
    'resilience': 'Test system ability to recover from disruptions.',
    'reliability': 'Test system consistency and dependability.',
    'availability': 'Test system uptime and accessibility.',
    'durability': 'Test data persistence and integrity.',
    'consistency': 'Test data accuracy across systems.',
    'isolation': 'Test transaction isolation and concurrency.',
    'atomicity': 'Test all-or-nothing transaction behavior.',
    'durability': 'Test committed transaction persistence.',
    'consistency': 'Test data integrity constraints.',
    'partition': 'Test system behavior during network partitions.',
    'latency': 'Test response time and delays.',
    'throughput': 'Test data processing rate.',
    'concurrency': 'Test simultaneous operations.',
    'deadlock': 'Test prevention of circular waiting.',
    'starvation': 'Test fair resource allocation.',
    'race-condition': 'Test timing-dependent bugs.',
    'memory-leak': 'Test memory usage and cleanup.',
    'garbage-collection': 'Test automatic memory management.',
    'resource-leak': 'Test proper resource cleanup.',
    'buffer-overflow': 'Test boundary checking and validation.',
    'injection': 'Test for code injection vulnerabilities.',
    'xss': 'Test for cross-site scripting attacks.',
    'csrf': 'Test for cross-site request forgery.',
    'clickjacking': 'Test for UI manipulation attacks.',
    'man-in-the-middle': 'Test for interception attacks.',
    'denial-of-service': 'Test for service disruption attacks.',
    'brute-force': 'Test for repeated attempt attacks.',
    'dictionary': 'Test for password guessing attacks.',
    'rainbow-table': 'Test for precomputed hash attacks.',
    'social-engineering': 'Test for human manipulation attacks.',
    'phishing': 'Test for deceptive communication attacks.',
    'malware': 'Test for malicious software detection.',
    'virus': 'Test for self-replicating malicious code.',
    'worm': 'Test for network-spreading malware.',
    'trojan': 'Test for disguised malicious software.',
    'ransomware': 'Test for data encryption attacks.',
    'spyware': 'Test for surveillance malware.',
    'adware': 'Test for advertising malware.',
    'rootkit': 'Test for system-level malware.',
    'backdoor': 'Test for unauthorized access methods.',
    'exploit': 'Test for vulnerability exploitation.',
    'patch': 'Test security update application.',
    'firewall': 'Test network traffic filtering.',
    'intrusion-detection': 'Test for security breach detection.',
    'intrusion-prevention': 'Test for security breach prevention.',
    'honeypot': 'Test decoy systems for attack detection.',
    'sandbox': 'Test isolated execution environments.',
    'virtualization': 'Test virtual machine security.',
    'container': 'Test container security and isolation.',
    'microsegmentation': 'Test network segmentation security.',
    'zero-trust': 'Test trust-based access control.',
    'least-privilege': 'Test minimal access permissions.',
    'defense-in-depth': 'Test layered security approach.',
    'risk-assessment': 'Test security risk evaluation.',
    'threat-modeling': 'Test threat identification and analysis.',
    'vulnerability-assessment': 'Test weakness identification.',
    'penetration-testing': 'Test simulated security attacks.',
    'red-team': 'Test adversarial security testing.',
    'blue-team': 'Test defensive security operations.',
    'purple-team': 'Test combined offensive and defensive testing.',
    'incident-response': 'Test security incident handling.',
    'forensic': 'Test digital evidence collection and analysis.',
    'chain-of-custody': 'Test evidence handling procedures.',
    'digital-signature': 'Test document authenticity verification.',
    'certificate': 'Test digital identity verification.',
    'public-key': 'Test asymmetric cryptography.',
    'symmetric-key': 'Test shared secret cryptography.',
    'hash-function': 'Test data integrity verification.',
    'blockchain': 'Test distributed ledger technology.',
    'smart-contract': 'Test automated contract execution.',
    'decentralized': 'Test distributed system architecture.',
    'consensus': 'Test agreement mechanisms in distributed systems.',
    'proof-of-work': 'Test computational effort verification.',
    'proof-of-stake': 'Test resource-based consensus.',
    'mining': 'Test cryptocurrency generation.',
    'wallet': 'Test digital asset storage.',
    'exchange': 'Test digital asset trading platforms.',
    'ico': 'Test initial coin offerings.',
    'defi': 'Test decentralized finance applications.',
    'nft': 'Test non-fungible tokens.',
    'dao': 'Test decentralized autonomous organizations.',
    'web3': 'Test next-generation internet technologies.',
    'metaverse': 'Test virtual reality environments.',
    'ar': 'Test augmented reality applications.',
    'vr': 'Test virtual reality applications.',
    'mr': 'Test mixed reality applications.',
    'iot': 'Test internet of things devices.',
    'edge-computing': 'Test distributed computing at network edges.',
    'fog-computing': 'Test hierarchical distributed computing.',
    'quantum': 'Test quantum computing applications.',
    'neural-network': 'Test brain-inspired computing.',
    'deep-learning': 'Test multi-layered neural networks.',
    'machine-learning': 'Test automated learning systems.',
    'artificial-intelligence': 'Test intelligent system capabilities.',
    'natural-language-processing': 'Test human language understanding.',
    'computer-vision': 'Test visual information processing.',
    'robotics': 'Test automated mechanical systems.',
    'automation': 'Test process automation technologies.',
    'industry-4': 'Test fourth industrial revolution technologies.',
    'digital-twin': 'Test virtual system representations.',
    'cyber-physical': 'Test integrated computational and physical systems.',
    'sustainable': 'Test environmentally friendly technologies.',
    'green-computing': 'Test energy-efficient computing.',
    'carbon-footprint': 'Test environmental impact measurement.',
    'renewable-energy': 'Test sustainable energy sources.',
    'circular-economy': 'Test resource reuse and recycling.',
    'sharing-economy': 'Test collaborative consumption models.',
    'platform-economy': 'Test digital platform business models.',
    'gig-economy': 'Test flexible labor arrangements.',
    'remote-work': 'Test distributed work arrangements.',
    'hybrid-work': 'Test combined office and remote work.',
    'work-life-balance': 'Test employee well-being optimization.',
    'diversity-inclusion': 'Test equitable workplace practices.',
    'equity': 'Test fair treatment and opportunities.',
    'inclusion': 'Test belonging and participation.',
    'mental-health': 'Test psychological well-being support.',
    'burnout': 'Test work-related stress prevention.',
    'resilience': 'Test adaptation to challenges.',
    'mindfulness': 'Test present-moment awareness practices.',
    'wellness': 'Test holistic health promotion.',
    'ergonomics': 'Test human factors in design.',
    'accessibility': 'Test universal design principles.',
    'universal-design': 'Test inclusive design approaches.',
    'user-centered-design': 'Test human-focused design processes.',
    'human-computer-interaction': 'Test human-technology interaction.',
    'user-experience': 'Test overall user satisfaction.',
    'user-interface': 'Test system interaction design.',
    'information-architecture': 'Test content organization and navigation.',
    'interaction-design': 'Test behavior and interaction planning.',
    'visual-design': 'Test aesthetic and communication design.',
    'motion-design': 'Test animation and transition design.',
    'responsive-design': 'Test cross-device compatibility.',
    'mobile-first': 'Test mobile-optimized design approach.',
    'progressive-enhancement': 'Test layered functionality approach.',
    'graceful-degradation': 'Test fallback functionality.',
    'feature-flags': 'Test conditional feature activation.',
    'a-b-testing': 'Test comparative feature evaluation.',
    'multivariate-testing': 'Test multiple variable combinations.',
    'user-research': 'Test user behavior and preference studies.',
    'usability-testing': 'Test user interface effectiveness.',
    'user-interview': 'Test direct user feedback collection.',
    'survey': 'Test structured feedback collection.',
    'focus-group': 'Test group discussion and feedback.',
    'ethnography': 'Test cultural and behavioral observation.',
    'card-sorting': 'Test information organization preferences.',
    'tree-testing': 'Test navigation and information finding.',
    'eye-tracking': 'Test visual attention and focus.',
    'heat-map': 'Test user interaction visualization.',
    'click-tracking': 'Test user behavior recording.',
    'session-recording': 'Test user interaction capture.',
    'analytics': 'Test data-driven decision making.',
    'kpi': 'Test key performance indicators.',
    'metric': 'Test measurement and evaluation criteria.',
    'goal': 'Test objective and target setting.',
    'objective': 'Test measurable outcome definition.',
    'strategy': 'Test long-term planning approach.',
    'tactic': 'Test specific action implementation.',
    'roadmap': 'Test timeline and milestone planning.',
    'milestone': 'Test significant achievement markers.',
    'deliverable': 'Test tangible output requirements.',
    'stakeholder': 'Test interested party management.',
    'requirement': 'Test need and specification definition.',
    'specification': 'Test detailed requirement description.',
    'user-story': 'Test functionality from user perspective.',
    'use-case': 'Test system behavior scenarios.',
    'scenario': 'Test situation and context description.',
    'persona': 'Test user archetype representation.',
    'journey': 'Test user experience flow.',
    'workflow': 'Test process and task sequence.',
    'process': 'Test systematic activity sequence.',
    'procedure': 'Test detailed step-by-step instructions.',
    'protocol': 'Test established rules and procedures.',
    'standard': 'Test accepted norms and practices.',
    'guideline': 'Test recommended practices and advice.',
    'best-practice': 'Test proven effective methods.',
    'framework': 'Test structured approach or methodology.',
    'methodology': 'Test systematic study or investigation.',
    'approach': 'Test way of dealing with something.',
    'technique': 'Test specific skill or method.',
    'tool': 'Test instrument or software for task completion.',
    'platform': 'Test foundation for application development.',
    'infrastructure': 'Test underlying system components.',
    'architecture': 'Test system design and structure.',
    'design-pattern': 'Test reusable solution template.',
    'anti-pattern': 'Test common problem solution.',
    'refactoring': 'Test code structure improvement.',
    'code-smell': 'Test potential code problem indicator.',
    'technical-debt': 'Test accumulated code maintenance cost.',
    'legacy-code': 'Test outdated system components.',
    'monolith': 'Test single large application.',
    'microservice': 'Test small independent services.',
    'modular': 'Test component-based architecture.',
    'component': 'Test reusable software unit.',
    'library': 'Test collection of reusable code.',
    'framework': 'Test software development support structure.',
    'sdk': 'Test software development kit.',
    'api': 'Test application programming interface.',
    'endpoint': 'Test API access point.',
    'webhook': 'Test event-driven API notification.',
    'rest': 'Test representational state transfer.',
    'graphql': 'Test query language for APIs.',
    'soap': 'Test simple object access protocol.',
    'websocket': 'Test bidirectional communication protocol.',
    'http': 'Test hypertext transfer protocol.',
    'https': 'Test secure hypertext transfer protocol.',
    'tcp': 'Test transmission control protocol.',
    'udp': 'Test user datagram protocol.',
    'ip': 'Test internet protocol.',
    'dns': 'Test domain name system.',
    'dhcp': 'Test dynamic host configuration protocol.',
    'nat': 'Test network address translation.',
    'vpn': 'Test virtual private network.',
    'firewall': 'Test network security barrier.',
    'router': 'Test network traffic director.',
    'switch': 'Test network connection device.',
    'hub': 'Test network connection point.',
    'modem': 'Test signal modulation/demodulation device.',
    'access-point': 'Test wireless network connection point.',
    'server': 'Test centralized computing resource.',
    'client': 'Test service requesting system.',
    'peer': 'Test equal network participant.',
    'node': 'Test network connection point.',
    'cluster': 'Test group of connected computers.',
    'datacenter': 'Test facility for computer systems.',
    'cloud': 'Test remote computing resources.',
    'hybrid-cloud': 'Test mixed local and remote resources.',
    'multi-cloud': 'Test multiple cloud provider usage.',
    'edge': 'Test network periphery computing.',
    'fog': 'Test distributed computing layer.',
    'serverless': 'Test event-driven computing.',
    'function-as-a-service': 'Test serverless function execution.',
    'platform-as-a-service': 'Test development platform service.',
    'infrastructure-as-a-service': 'Test virtualized computing resources.',
    'software-as-a-service': 'Test cloud-based software applications.',
    'database': 'Test structured data storage system.',
    'relational': 'Test table-based data model.',
    'nosql': 'Test non-relational data models.',
    'document': 'Test document-oriented database.',
    'graph': 'Test relationship-focused database.',
    'key-value': 'Test simple key-based storage.',
    'column-family': 'Test column-oriented storage.',
    'time-series': 'Test timestamped data storage.',
    'spatial': 'Test location-based data storage.',
    'search-engine': 'Test information retrieval system.',
    'cache': 'Test high-speed data storage.',
    'message-queue': 'Test asynchronous communication.',
    'stream-processing': 'Test real-time data processing.',
    'data-warehouse': 'Test large-scale data storage.',
    'data-lake': 'Test raw data storage repository.',
    'etl': 'Test extract transform load process.',
    'data-pipeline': 'Test automated data flow.',
    'data-catalog': 'Test data asset inventory.',
    'data-governance': 'Test data management policies.',
    'data-quality': 'Test data accuracy and completeness.',
    'data-lineage': 'Test data origin and transformation tracking.',
    'metadata': 'Test data about data.',
    'schema': 'Test data structure definition.',
    'index': 'Test data lookup optimization.',
    'partition': 'Test data distribution strategy.',
    'replication': 'Test data redundancy strategy.',
    'backup': 'Test data recovery strategy.',
    'recovery': 'Test system restoration process.',
    'disaster-recovery': 'Test major incident response.',
    'high-availability': 'Test system uptime maximization.',
    'fault-tolerance': 'Test failure resistance.',
    'load-balancing': 'Test traffic distribution.',
    'scalability': 'Test growth capability.',
    'elasticity': 'Test dynamic resource adjustment.',
    'auto-scaling': 'Test automatic resource adjustment.',
    'monitoring': 'Test system observation.',
    'logging': 'Test event recording.',
    'alerting': 'Test notification system.',
    'tracing': 'Test request tracking.',
    'profiling': 'Test performance analysis.',
    'benchmarking': 'Test performance comparison.',
    'optimization': 'Test performance improvement.',
    'tuning': 'Test configuration adjustment.',
    'debugging': 'Test issue identification.',
    'troubleshooting': 'Test problem resolution.',
    'root-cause-analysis': 'Test underlying problem identification.',
    'incident-management': 'Test issue handling process.',
    'change-management': 'Test modification control.',
    'configuration-management': 'Test system configuration control.',
    'release-management': 'Test software deployment control.',
    'deployment': 'Test software installation.',
    'rollback': 'Test version reversion.',
    'blue-green': 'Test zero-downtime deployment.',
    'canary': 'Test gradual deployment.',
    'feature-toggle': 'Test feature activation control.',
    'continuous-integration': 'Test automated code integration.',
    'continuous-delivery': 'Test automated deployment preparation.',
    'continuous-deployment': 'Test automated production deployment.',
    'devops': 'Test development and operations integration.',
    'site-reliability-engineering': 'Test system reliability focus.',
    'infrastructure-as-code': 'Test infrastructure definition as code.',
    'configuration-as-code': 'Test configuration definition as code.',
    'pipeline-as-code': 'Test deployment pipeline definition as code.',
    'gitops': 'Test git-based operations.',
    'chatops': 'Test chat-based operations.',
    'version-control': 'Test code change tracking.',
    'branching': 'Test code development isolation.',
    'merging': 'Test code integration.',
    'conflict-resolution': 'Test merge issue resolution.',
    'pull-request': 'Test code review process.',
    'code-review': 'Test code quality assessment.',
    'pair-programming': 'Test collaborative coding.',
    'mob-programming': 'Test group coding.',
    'test-driven-development': 'Test code writing driven by tests.',
    'behavior-driven-development': 'Test business requirement focused development.',
    'domain-driven-design': 'Test business domain focused design.',
    'agile': 'Test iterative development approach.',
    'scrum': 'Test agile project management framework.',
    'kanban': 'Test visual task management.',
    'lean': 'Test waste reduction methodology.',
    'waterfall': 'Test sequential development approach.',
    'spiral': 'Test risk-driven development.',
    'extreme-programming': 'Test agile software development.',
    'crystal': 'Test lightweight methodology.',
    'feature-driven-development': 'Test feature-centric development.',
    'rapid-application-development': 'Test accelerated development.',
    'dynamic-systems-development': 'Test iterative prototyping.',
    'unified-process': 'Test use-case driven development.',
    'rational-unified-process': 'Test comprehensive development framework.',
    'open-source': 'Test publicly available source code.',
    'proprietary': 'Test privately owned software.',
    'free-software': 'Test freedom-respecting software.',
    'copyleft': 'Test license requiring derivative sharing.',
    'permissive-license': 'Test flexible usage license.',
    'mit-license': 'Test permissive open source license.',
    'apache-license': 'Test business-friendly open source license.',
    'gpl-license': 'Test copyleft open source license.',
    'bsd-license': 'Test academic open source license.',
    'mozilla-license': 'Test file-based open source license.',
    'creative-commons': 'Test content sharing license.',
    'public-domain': 'Test unrestricted content.',
    'intellectual-property': 'Test intangible asset rights.',
    'copyright': 'Test original work protection.',
    'patent': 'Test invention protection.',
    'trademark': 'Test brand identifier protection.',
    'trade-secret': 'Test confidential information protection.',
    'nda': 'Test non-disclosure agreement.',
    'cla': 'Test contributor license agreement.',
    'dco': 'Test developer certificate of origin.',
    'license': 'Test usage permission document.',
    'attribution': 'Test credit requirement.',
    'share-alike': 'Test derivative sharing requirement.',
    'no-derivatives': 'Test modification prohibition.',
    'non-commercial': 'Test commercial use prohibition.',
    'commercial': 'Test business use permission.',
    'royalty-free': 'Test payment-free usage.',
    'perpetual': 'Test permanent license.',
    'terminable': 'Test cancellable license.',
    'exclusive': 'Test sole rights grant.',
    'non-exclusive': 'Test shared rights grant.',
    'sublicensable': 'Test rights transfer permission.',
    'transferable': 'Test rights assignment permission.',
    'revocable': 'Test rights withdrawal possibility.',
    'irrevocable': 'Test permanent rights grant.',
    'worldwide': 'Test global geographic scope.',
    'territorial': 'Test limited geographic scope.',
    'time-limited': 'Test duration-based license.',
    'perpetual': 'Test permanent license.',
    'personal': 'Test individual use license.',
    'organizational': 'Test group use license.',
    'enterprise': 'Test large organization license.',
    'academic': 'Test educational institution license.',
    'non-profit': 'Test charitable organization license.',
    'government': 'Test public sector license.',
    'individual': 'Test personal use license.',
    'professional': 'Test business use license.',
    'developer': 'Test software creation license.',
    'end-user': 'Test software usage license.',
    'redistributable': 'Test sharing permission.',
    'non-redistributable': 'Test sharing prohibition.',
    'modifiable': 'Test change permission.',
    'non-modifiable': 'Test change prohibition.',
    'reverse-engineerable': 'Test analysis permission.',
    'non-reverse-engineerable': 'Test analysis prohibition.',
    'embedded': 'Test inclusion in other works permission.',
    'standalone': 'Test independent use requirement.',
    'bundled': 'Test package inclusion permission.',
    'unbundled': 'Test separate distribution requirement.',
    'source-code': 'Test human-readable code access.',
    'object-code': 'Test machine-readable code access.',
    'binary': 'Test compiled executable access.',
    'documentation': 'Test usage instructions access.',
    'support': 'Test assistance availability.',
    'warranty': 'Test quality guarantee.',
    'liability': 'Test responsibility limitation.',
    'indemnification': 'Test loss compensation.',
    'disclaimer': 'Test responsibility denial.',
    'limitation': 'Test scope restriction.',
    'jurisdiction': 'Test legal authority.',
    'governing-law': 'Test applicable legal system.',
    'arbitration': 'Test dispute resolution method.',
    'venue': 'Test legal proceeding location.',
    'class-action': 'Test group lawsuit permission.',
    'severability': 'Test provision independence.',
    'entire-agreement': 'Test complete understanding.',
    'amendment': 'Test modification process.',
    'termination': 'Test license end process.',
    'survival': 'Test post-termination obligations.',
    'force-majeure': 'Test uncontrollable event handling.',
    'assignment': 'Test rights transfer process.',
    'successor': 'Test rights inheritance.',
    'third-party': 'Test external party rights.',
    'beneficial-owner': 'Test actual rights holder.',
    'licensee': 'Test rights recipient.',
    'licensor': 'Test rights grantor.',
    'copyright-holder': 'Test work ownership.',
    'author': 'Test content creator.',
    'contributor': 'Test content provider.',
    'maintainer': 'Test project caretaker.',
    'sponsor': 'Test project supporter.',
  };

  // Match keywords in the title to find appropriate description
  for (const [keyword, desc] of Object.entries(taskDescriptions)) {
    if (doc.has(keyword) || title.toLowerCase().includes(keyword)) {
      description = desc;
      break;
    }
  }

  // Default description if no match found
  if (!description) {
    description = 'Complete the task as described in the title.';
  }

  return description;
}

function generateAllFromTitle(title, description = '') {
  const priority = analyzeTaskPriority(title, description);
  const tags = extractKeywords(title + ' ' + description);
  const descriptionGenerated = generateAIDescription(title);
  return {
    priority,
    tags,
    description: descriptionGenerated,
  };
}

// Export all functions
module.exports = {
  analyzeTaskPriority,
  extractKeywords,
  searchTasks,
  generateAISuggestions,
  generateAIDescription,
  generateAllFromTitle,
};
    